version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    networks:
      - datingApp

  backend:
    build: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - dev-db
    networks:
      - datingApp
    command: >
      sh -c "npx prisma generate && npm run start:prod"

networks:
  datingApp:
